name: variables

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        required: true
        type: string

env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  ejecucion:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # variables locales
      - run: echo 'Hi ${{ env.mascot }}'  # variables locales
        env:
          mascot: ${{ inputs.deploy_target }}
      - name: ${{ vars.JOB_NAME }} #using env variables
        run: echo "using environment variables $var1"
        with:
          var1: ${{ vars.JOB_NAME }}
      - name: ${{ vars.USE_VARIABLES }} #using env variables
        if: ${{ vars.USE_VARIABLES == 'true' }} ##using repository variable
        run: echo "using repository variables ${{ vars.USE_VARIABLES }}"
      - name: ${{ github.ref }}
        if: ${{ github.ref == 'refs/heads/main' }} ## using default variables
        run: echo "using default variables $GITHUB_REF"
      - name: ${{ inputs.deploy_target }}
        run: echo "using input ${{ inputs.deploy_target }}"
